version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: tradewise-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: tradewise-db
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - tradewise-network
    command: mongod --auth

  # Optional: MongoDB Express for database management UI
  mongo-express:
    image: mongo-express:1.0.0
    container_name: tradewise-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      - mongodb
    networks:
      - tradewise-network

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local

networks:
  tradewise-network:
    driver: bridge
